//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity_Importaciones_Rpt : DbContext
    {
        public Entity_Importaciones_Rpt()
            : base("name=Entity_Importaciones_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwIMP_Rpt001> vwIMP_Rpt001 { get; set; }
        public DbSet<vwIMP_Rpt002> vwIMP_Rpt002 { get; set; }
    }
}
