//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_Rpt001
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public string IdTipoDocumento { get; set; }
        public string numDocumento { get; set; }
        public decimal IdCliente { get; set; }
        public string nombreCliente { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public int IdCalendario { get; set; }
        public Nullable<int> AnioFiscal { get; set; }
        public string NombreMes { get; set; }
        public string NombreCortoFecha { get; set; }
        public decimal IdProducto { get; set; }
        public string nombreProducto { get; set; }
        public double vt_cantidad { get; set; }
        public double vt_PrecioFinal { get; set; }
        public double vt_Subtotal { get; set; }
        public double vt_iva { get; set; }
        public double vt_total { get; set; }
        public string Su_Descripcion { get; set; }
        public string IdCategoria { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdSubgrupo { get; set; }
        public string ca_Categoria { get; set; }
        public string nom_linea { get; set; }
        public string nom_grupo { get; set; }
        public string nom_subgrupo { get; set; }
        public int Idtipo_cliente { get; set; }
        public string Descripcion_tip_cliente { get; set; }
        public string vt_Observacion { get; set; }
        public int IdVendedor { get; set; }
        public string Vendedor { get; set; }
    }
}
