CREATE TABLE [ats].[compras] (
    [IdEmpresa]         INT             NOT NULL,
    [IdPeriodo]         INT             NOT NULL,
    [Secuencia]         INT             NOT NULL,
    [codSustento]       VARCHAR (2)     NOT NULL,
    [tpIdProv]          VARCHAR (2)     NOT NULL,
    [idProv]            VARCHAR (2)     NOT NULL,
    [tipoComprobante]   VARCHAR (3)     NOT NULL,
    [parteRel]          VARCHAR (2)     NOT NULL,
    [tipoProv]          VARCHAR (2)     NOT NULL,
    [denopr]            VARCHAR (500)   NOT NULL,
    [fechaRegistro]     DATE            NOT NULL,
    [establecimiento]   VARCHAR (3)     NOT NULL,
    [puntoEmision]      VARCHAR (3)     NOT NULL,
    [secuencial]        VARCHAR (9)     NOT NULL,
    [fechaEmision]      DATE            NOT NULL,
    [autorizacion]      VARCHAR (49)    NOT NULL,
    [baseNoGraIva]      NUMERIC (12, 2) NOT NULL,
    [baseImponible]     NUMERIC (12, 2) NOT NULL,
    [baseImpGrav]       NUMERIC (12, 2) NOT NULL,
    [baseImpExe]        NUMERIC (12, 2) NOT NULL,
    [montoIce]          NUMERIC (12, 2) NOT NULL,
    [montoIva]          NUMERIC (12, 2) NOT NULL,
    [valRetBien10]      NUMERIC (12, 2) NOT NULL,
    [valRetServ20]      NUMERIC (12, 2) NOT NULL,
    [valorRetBienes]    NUMERIC (12, 2) NOT NULL,
    [valRetServ50]      NUMERIC (12, 2) NOT NULL,
    [valorRetServicios] NUMERIC (12, 2) NOT NULL,
    [valRetServ100]     NUMERIC (12, 2) NOT NULL,
    [pagoLocExt]        VARCHAR (2)     NOT NULL,
    [denopago]          VARCHAR (2)     NULL,
    [paisEfecPago]      VARCHAR (2)     NULL,
    [formaPago]         VARCHAR (2)     NULL,
    CONSTRAINT [PK_compras] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdPeriodo] ASC, [Secuencia] ASC)
);

