/*
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'ACTF_001', N'Revalorización de activo', N'ACTF', N'web.VWACTF_001', 0, N'web.SPACTF_001', N'ACTF_001_Info', N'ACTF_001_Data', N'ACTF_001_Bus', N'ACTF_001_Rpt', N'Reportes', N'ActivoFijoReportes', N'ACTF_001', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'ACTF_002', N'Venta de activo', N'ACTF', N'web.VWACTF_002', 0, N'web.SPACTF_002', N'ACTF_002_Info', N'ACTF_002_Data', N'ACTF_002_Bus', N'ACTF_002_Rpt', N'Reportes', N'ActivoFijoReportes', N'ACTF_002', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'ACTF_003', N'Retiro de activo', N'ACTF', N'web.VWACTF_003', 0, N'web.SPACTF_003', N'ACTF_003_Info', N'ACTF_003_Data', N'ACTF_003_Bus', N'ACTF_003_Rpt', N'Reportes', N'ActivoFijoReportes', N'ACTF_003', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'CONTA_001', N'COMPROBANTE CONTABLE', N'CONTA', N'web.VWCONTA_001', 0, N'web.SPCONTA_001', N'CONTA_001_Info', N'CONTA_001_Data', N'CONTA_001_Bus', N'CONTA_001_Rpt', N'Reportes', N'ContabilidadReportes', N'CONTA_001', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'INV_001', N'Ingresos', N'INV', N'web.VWINV_001', 0, NULL, N'INV_001_Info', N'INV_001_Data', N'INV_001_Bus', N'INV_001_Rpt', N'Reportes', N'InventarioReportes', N'INV_001', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'INV_002', N'Ingresos', N'INV', N'web.VWINV_002', 0, NULL, N'INV_002_Info', N'INV_002_Data', N'INV_002_Bus', N'INV_002_Rpt', N'Reportes', N'InventarioReportes', N'INV_002', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'INV_003', N'Listado inventario fisico', N'INV', N'web.VWINV_003', 1, N'web.SPINV_003', N'INV_003_Info', N'INV_003_Data', N'INV_003_Bus', N'INV_003_Rpt', N'Reportes', N'InventarioReportes', N'INV_003', 1, 0, 0, NULL)
INSERT [web].[tb_sis_reporte] ([CodReporte], [nom_reporte], [CodModulo], [rpt_vista], [rpt_usa_store_procedure], [rpt_store_procedure], [rpt_clase_info], [rpt_clase_data], [rpt_clase_bus], [rpt_clase_rpt], [mvc_area], [mvc_controlador], [mvc_accion], [estado], [se_muestra_administrador_reportes], [orden], [observacion]) VALUES (N'INV_004', N'Matriz de inventario', N'INV', N'web.VWINV_004', 0, NULL, N'INV_004__Info', N'INV_004_Data', N'INV_004_Bus', N'INV_004_Rpt', N'Reportes', N'InventarioReportes', N'INV_004', 1, 0, 0, NULL)
*/

