//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesFacturacion_Natu_Rpt : DbContext
    {
        public EntitiesFacturacion_Natu_Rpt()
            : base("name=EntitiesFacturacion_Natu_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwFAC_CUS_NAT_Rpt002> vwFAC_CUS_NAT_Rpt002 { get; set; }
    }
}
