//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class caj_Caja_Movimiento_Tipo_grupo
    {
        public caj_Caja_Movimiento_Tipo_grupo()
        {
            this.caj_Caja_Movimiento_Tipo = new HashSet<caj_Caja_Movimiento_Tipo>();
        }
    
        public int IdTipoMovi_grupo { get; set; }
        public string tg_descripcion { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<caj_Caja_Movimiento_Tipo> caj_Caja_Movimiento_Tipo { get; set; }
    }
}
