//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_Vendedor
    {
        public fa_Vendedor()
        {
            this.fa_devol_venta = new HashSet<fa_devol_venta>();
            this.fa_notaCreDeb = new HashSet<fa_notaCreDeb>();
            this.fa_proforma = new HashSet<fa_proforma>();
            this.fa_vendedor_x_ro_empleado = new HashSet<fa_vendedor_x_ro_empleado>();
            this.fa_VendedorxSucursal = new HashSet<fa_VendedorxSucursal>();
            this.fa_factura = new HashSet<fa_factura>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdVendedor { get; set; }
        public string Codigo { get; set; }
        public string Ve_Vendedor { get; set; }
        public string ve_cedula { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Estado { get; set; }
        public string MotivoAnula { get; set; }
    
        public virtual ICollection<fa_devol_venta> fa_devol_venta { get; set; }
        public virtual ICollection<fa_notaCreDeb> fa_notaCreDeb { get; set; }
        public virtual ICollection<fa_proforma> fa_proforma { get; set; }
        public virtual ICollection<fa_vendedor_x_ro_empleado> fa_vendedor_x_ro_empleado { get; set; }
        public virtual ICollection<fa_VendedorxSucursal> fa_VendedorxSucursal { get; set; }
        public virtual ICollection<fa_factura> fa_factura { get; set; }
    }
}
