//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class imp_liquidacion_det_x_imp_orden_compra_ext
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int IdEmpresa_oe { get; set; }
        public decimal IdOrdenCompra_ext { get; set; }
        public string observacion { get; set; }
    
        public virtual imp_liquidacion imp_liquidacion { get; set; }
        public virtual imp_orden_compra_ext imp_orden_compra_ext { get; set; }
    }
}
