//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Producto_imagenes
    {
        public int IdEmpresa { get; set; }
        public decimal IdProducto { get; set; }
        public int Secuencia { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual in_Producto in_Producto { get; set; }
    }
}
