//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_presupuesto_tipoRubro
    {
        public pre_presupuesto_tipoRubro()
        {
            this.pre_presupuesto = new HashSet<pre_presupuesto>();
        }
    
        public string IdTipoRubro { get; set; }
        public string Descripcion { get; set; }
        public string Tabla { get; set; }
    
        public virtual ICollection<pre_presupuesto> pre_presupuesto { get; set; }
    }
}
