//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_cliente_vista_previa
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public string Codigo { get; set; }
        public decimal IdPersona { get; set; }
        public int IdSucursal { get; set; }
        public string nom_sucursal { get; set; }
        public string IdTipoCredito { get; set; }
        public int cl_plazo { get; set; }
        public string IdCtaCble_cxc { get; set; }
        public string nom_CtaCble_cxc { get; set; }
        public string IdCtaCble_Anti { get; set; }
        public string nom_CtaCble_Anti { get; set; }
        public string cl_observacion { get; set; }
        public string IdCiudad { get; set; }
        public string Descripcion_Ciudad { get; set; }
        public double cl_Cupo { get; set; }
        public string Estado { get; set; }
        public string Mail_Principal { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_razonSocial { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_celular { get; set; }
        public string pe_correo { get; set; }
        public Nullable<int> pe_fax { get; set; }
        public Nullable<int> pe_casilla { get; set; }
        public string IdProvincia { get; set; }
        public string IdPais { get; set; }
        public string IdCtaCble_cxc_Credito { get; set; }
        public Nullable<bool> es_empresa_relacionada { get; set; }
    }
}
