//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_producto
    {
        public string tp_descripcion { get; set; }
        public string ca_Categoria { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_codigo_barra { get; set; }
        public int IdProductoTipo { get; set; }
        public string IdPresentacion { get; set; }
        public string IdCategoria { get; set; }
        public string pr_descripcion { get; set; }
        public string pr_observacion { get; set; }
        public string IdUnidadMedida { get; set; }
        public int pr_pedidos { get; set; }
        public int IdMarca { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string pr_motivoAnulacion { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Estado { get; set; }
        public string pr_descripcion_2 { get; set; }
        public int IdLinea { get; set; }
        public int IdGrupo { get; set; }
        public int IdSubGrupo { get; set; }
        public string IdNaturaleza { get; set; }
        public int IdMotivo_Vta { get; set; }
        public string IdUnidadMedida_Consumo { get; set; }
        public string nom_linea { get; set; }
        public string nom_grupo { get; set; }
        public string nom_subgrupo { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public bool Aparece_modu_Ventas { get; set; }
        public bool Aparece_modu_Compras { get; set; }
        public bool Aparece_modu_Inventario { get; set; }
        public bool Aparece_modu_Activo_F { get; set; }
        public string tp_ManejaInven { get; set; }
        public Nullable<decimal> IdProducto_padre { get; set; }
        public Nullable<System.DateTime> lote_fecha_fab { get; set; }
        public Nullable<System.DateTime> lote_fecha_vcto { get; set; }
        public string lote_num_lote { get; set; }
        public string pr_descripcion_padre { get; set; }
        public Nullable<bool> tp_ManejaLote { get; set; }
        public string tp_EsCombo { get; set; }
        public Nullable<bool> se_distribuye { get; set; }
        public Nullable<double> precio_1 { get; set; }
        public Nullable<double> precio_2 { get; set; }
        public string signo_2 { get; set; }
        public Nullable<double> porcentaje_2 { get; set; }
        public Nullable<double> precio_3 { get; set; }
        public string signo_3 { get; set; }
        public Nullable<double> porcentaje_3 { get; set; }
        public Nullable<double> precio_4 { get; set; }
        public string signo_4 { get; set; }
        public Nullable<double> porcentaje_4 { get; set; }
        public Nullable<double> precio_5 { get; set; }
        public string signo_5 { get; set; }
        public Nullable<double> porcentaje_5 { get; set; }
        public string pr_codigo2 { get; set; }
        public string nom_presentacion { get; set; }
    }
}
